services:
  - type: web
    name: truck-dashboard
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
